Enable printing command lines
Firstyear/cargo-packaging pull request #2
Opened 2022-11-03 18:17 UTC by jengelh

openSUSE is using --disable-silent-rules in many packages; apply the same for cargo, but on a global scale.

2022-11-03 21:49 UTC, Firstyear requested changes
What benefit will this bring to packagers/developers? It seems like this will just make a lot of verbose noise that isn't needed. When cargo errors it dumps the full cmdline that was in use anyway, so this doesn't even assist with error tracing if that occurs.

2022-11-03 21:49 UTC, Firstyear commented on macros.cargo
> +    --offline --release -v \
You don't need the duplicate here since cargo_common_opts is already in use.

2022-11-03 22:27 UTC, jengelh commented
> What benefit will this bring to packagers/developers?

Seeing the flags that were used even when the build _doesn't_ fail, especially to confirm (by humans or automated tools) that the expected ones are in it. post-build-checks [analyzed command lines](https://github.com/openSUSE/post-build-checks/blob/b3024ef7443ef0a77cb227ce824e3be2010aa071/checks-data/check_gcc_output#L220) that way to ensure conformance with distro policies (it has moved to a smarter method but which is not applicable to rust).

2022-11-03 22:37 UTC, Firstyear commented
> > What benefit will this bring to packagers/developers?
> 
> Seeing the flags that were used even when the build _doesn't_ fail, especially to confirm (by humans or automated tools) that the expected ones are in it. post-build-checks [analyzed command lines](https://github.com/openSUSE/post-build-checks/blob/b3024ef7443ef0a77cb227ce824e3be2010aa071/checks-data/check_gcc_output#L220) that way to ensure conformance with distro policies (it has moved to a smarter method but which is not applicable to rust).

Currently there is no post-build check that relies on this anyway for rust. When we do set flags they are in an environment variable that rust reads, and isn't displayed on the CLI. So adding verbosity won't help here for checking "did it do the right thing". You need to check in other ways. 

I think the approach here is wrong - this PR is prescribing a solution without framing the problem. When it needs to however frame the *problem* and examine it in the context of Rust (not C).

2022-11-03 22:37 UTC, closed without merging

2024-08-07 08:12 UTC, brjsp commented
The problem i have noticed is that some packages i maintain (signal-desktop and dependents) do bizarre FFI shenanigans. I need to make sure that the C code is built with the correct optflags, and also need to see the linker commandline. I add `--verbose` to RUSTFLAGS but that is not even sufficient. To see <i>any</i> sort of useful build output i also have to:

* run `cargo -vv auditable -vv` (otherwise build script output gets silenced by cargo)
* `export RUSTC_LOG='rustc_codegen_ssa::back::link=info'` (to see LTO linker warnings)
* `export CC_ENABLE_DEBUG_OUTPUT=1` (otherwise build script output gets silenced by some <i>different</i> program)
* `export CARGO_TERM_VERBOSE=true` (I forgot even what that was for)

2024-08-07 23:44 UTC, Firstyear commented
In these cases can you not just do `%{cargo_build} -v` ?

2024-08-08 05:47 UTC, brjsp commented
> In these cases can you not just do `%{cargo_build} -v` ?

I do not use `%cargo_build` for two reasons:

* The package must build on both openSUSE and Fedora (This is why i reported <a href="https://bugzilla.suse.com/show_bug.cgi?id=1212226">bsc#1212226</a> to you previously, thanks for fixing that!)
* I need to inject some per-package feature flags to rustc to build the correct target. Sometimes it's more reliable to <a href="https://build.opensuse.org/projects/network:im:signal/packages/libsignal/files/build_node_bridge-inject-options.patch?expand=1">hack the upstream build script to do what we want</a> than to extract the command lines by some other means.

(Posting this just so posterity will know how much of a mess Rust is from a packager's perspective)

2024-08-08 05:55 UTC, Firstyear commented
> > In these cases can you not just do `%{cargo_build} -v` ?

I'm not against this btw, I just think there needs to be a clear "we can't do this with what we already have" use case. 

> 
> I do not use `%cargo_build` for two reasons:
> 
>     * The package must build on both openSUSE and Fedora (This is why i reported [bsc#1212226](https://bugzilla.suse.com/show_bug.cgi?id=1212226) to you previously, thanks for fixing that!)

No problems :) 

> 
>     * I need to inject some per-package feature flags to rustc to build the correct target. Sometimes it's more reliable to [hack the upstream build script to do what we want](https://build.opensuse.org/projects/network:im:signal/packages/libsignal/files/build_node_bridge-inject-options.patch?expand=1) than to extract the command lines by some other means.
> 
> 
> (Posting this just so posterity will know how much of a mess Rust is from a packager's perspective)

The signal issue you posted is because libsignal is wrapping cargo, which means that the indirection there is the problem rather than anything rust does. 

cargo auditable strictly speaking *isn't* required. It's just there for supporting SBOM, so if you're willing to generate the provides statements manually, you can just drop it. 

And the other part of this mess is how things are approached in other distros. Fedora especially makes a mess of this, and has a lot of "anti-patterns" which is really difficult to escape from.